# /project_folder/docker-compose.yml

services:
  db:
    image: mysql:8
    container_name: dialogues-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}        
      MYSQL_USER: ${DB_USER}                  
      MYSQL_PASSWORD: ${DB_PASSWORD}         
    ports:
      - "3306:3306"
    volumes:
      - dialogues-db-data:/var/lib/mysql

volumes:
  dialogues-db-data:

#docker-compose up -d
#docker exec -it dialogues-mysql mysql -u root -p

# SHOW TABLES;
# DESCRIBE liturgical_days;
# SELECT * FROM liturgical_days LIMIT 10;
# SELECT COUNT(*) FROM liturgical_days WHERE year = 2024 AND region = 'US';
# SELECT date, name, grade_name, liturgical_season FROM liturgical_days WHERE date = '2024-12-25';