# /project_folder/docker-compose.yml

version: '3.8'

services:
  db:
    image: mysql:8
    container_name: dialogues-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}        
      MYSQL_USER: ${DB_USER}                  
      MYSQL_PASSWORD: ${DB_PASSWORD}         
    ports:
      - "3306:3306"
    volumes:
      - dialogues-db-data:/var/lib/mysql

volumes:
  dialogues-db-data:

#docker-compose up -d