"""Initial database schema

Revision ID: 0be88e1c2394
Revises: 
Create Date: 2025-08-01 03:04:59.089446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be88e1c2394'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liturgies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('WORD', 'PRAYER', name='liturgytype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('theme', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liturgies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liturgies_date'), ['date'], unique=False)

    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('CHURCH', 'GROUP', 'CHARITY', 'ORDER', 'HOSPITAL', 'SCHOOL', 'OTHER', name='orgtype'), nullable=False),
    sa.Column('contact', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organisations_name'), ['name'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('ADMIN', 'EDITOR', 'WRITER', 'READER', name='roletype'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('other_names', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_authorized', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('discourse_blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discourse_blogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discourse_blogs_date_posted'), ['date_posted'], unique=False)
        batch_op.create_index(batch_op.f('ix_discourse_blogs_reference'), ['reference'], unique=True)

    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liturgy_id', sa.Integer(), nullable=False),
    sa.Column('reading_number', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['liturgy_id'], ['liturgies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('discourse_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('discourse_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('date_commented', sa.DateTime(), nullable=True),
    sa.Column('is_audited', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['discourse_id'], ['discourse_blogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discourse_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('REPOSITORY', 'JOURNAL', 'ACADEMIC_PAPER', 'BLOG', 'COMMENTARY', 'TUTORIAL', 'LECTURE', 'VIDEO', name='resourcetype'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('medium', sa.String(length=100), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['discourse_id'], ['discourse_blogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resources')
    op.drop_table('discourse_comments')
    op.drop_table('user_roles')
    op.drop_table('readings')
    with op.batch_alter_table('discourse_blogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discourse_blogs_reference'))
        batch_op.drop_index(batch_op.f('ix_discourse_blogs_date_posted'))

    op.drop_table('discourse_blogs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('roles')
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organisations_name'))

    op.drop_table('organisations')
    with op.batch_alter_table('liturgies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liturgies_date'))

    op.drop_table('liturgies')
    # ### end Alembic commands ###
