"""empty message

Revision ID: 2887021b2d5d
Revises: a8443ba3d6cc
Create Date: 2025-08-09 16:38:02.565689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2887021b2d5d'
down_revision = 'a8443ba3d6cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discourse_blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discourse_blogs', schema=None) as batch_op:
        batch_op.drop_column('featured_image')

    # ### end Alembic commands ###
