"""Add education, contact, and career to User model

Revision ID: 766051753814
Revises: eceae114776c
Create Date: 2025-08-26 10:42:18.849584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766051753814'
down_revision = 'eceae114776c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('career', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('career')
        batch_op.drop_column('contact')
        batch_op.drop_column('education')

    # ### end Alembic commands ###
