"""empty message

Revision ID: a8443ba3d6cc
Revises: 582bcb6928ad
Create Date: 2025-08-03 11:18:01.859398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8443ba3d6cc'
down_revision = '582bcb6928ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.alter_column('medium',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('VIDEO', 'AUDIO', 'IMAGE', 'PDF', 'BOOK', 'OTHER', name='resourcemedium'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.alter_column('medium',
               existing_type=sa.Enum('VIDEO', 'AUDIO', 'IMAGE', 'PDF', 'BOOK', 'OTHER', name='resourcemedium'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
