"""empty message

Revision ID: b16aad9eef33
Revises: 0be88e1c2394
Create Date: 2025-08-01 06:05:25.480743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16aad9eef33'
down_revision = '0be88e1c2394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('organization_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.alter_column('other_names',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.alter_column('other_names',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('website')
        batch_op.drop_column('organization_name')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
