"""Manually add BOOK and update WEBPAGE to ResourceType enum

Revision ID: bfe06e81c0c6
Revises: c312e08ae404
Create Date: 2025-08-25 21:18:55.657140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe06e81c0c6'
down_revision = 'c312e08ae404'
branch_labels = None
depends_on = None


new_resource_types = [
    'REPOSITORY', 'JOURNAL', 'ACADEMIC_PAPER', 'BLOG', 'BOOK', 'COMMENTARY', 
    'TUTORIAL', 'LECTURE', 'WEBPAGE', 'SCRIPTURE', 'SERMON', 'OTHER'
]

# This is the old list currently in your database
old_resource_types = [
    'REPOSITORY', 'JOURNAL', 'ACADEMIC_PAPER', 'BLOG', 'COMMENTARY', 
    'TUTORIAL', 'LECTURE', 'PAGE', 'SCRIPTURE', 'SERMON', 'OTHER'
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resources', 'type',
               existing_type=sa.Enum(*old_resource_types, name='resourcetype'),
               type_=sa.Enum(*new_resource_types, name='resourcetype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resources', 'type',
               existing_type=sa.Enum(*new_resource_types, name='resourcetype'),
               type_=sa.Enum(*old_resource_types, name='resourcetype'),
               existing_nullable=False)
    # ### end Alembic commands ###



