"""enum update resourcetype

Revision ID: c312e08ae404
Revises: a5ac1fd1bea8
Create Date: 2025-08-21 18:44:51.976954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c312e08ae404'
down_revision = 'a5ac1fd1bea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.alter_column('medium',
               existing_type=mysql.ENUM('VIDEO', 'AUDIO', 'IMAGE', 'DOCUMENT', 'FILE_FOLDER', 'WEBSITE', 'BIBLE', 'BOOK', 'OTHER'),
               type_=sa.Enum('VIDEO', 'AUDIO', 'IMAGE', 'DOCUMENT', 'FILE_FOLDER', 'ONLINE', 'BIBLE', 'PRINT', 'OTHER', name='resourcemedium'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.alter_column('medium',
               existing_type=sa.Enum('VIDEO', 'AUDIO', 'IMAGE', 'DOCUMENT', 'FILE_FOLDER', 'ONLINE', 'BIBLE', 'PRINT', 'OTHER', name='resourcemedium'),
               type_=mysql.ENUM('VIDEO', 'AUDIO', 'IMAGE', 'DOCUMENT', 'FILE_FOLDER', 'WEBSITE', 'BIBLE', 'BOOK', 'OTHER'),
               existing_nullable=True)

    # ### end Alembic commands ###
