"""Add Charity and CharityCategory models

Revision ID: e08eaf379e4e
Revises: 5d762d4f0fc1
Create Date: 2025-08-27 15:54:15.011753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e08eaf379e4e'
down_revision = '5d762d4f0fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('logo_image', sa.String(length=255), nullable=True),
    sa.Column('is_vetted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charities_name'), ['name'], unique=False)

    op.create_table('charity_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('CHILDREN', 'WELFARE', 'EDUCATION', 'HEALTH', 'FOOD', 'WAR', 'FAITH', 'DISASTER', 'ENVIRONMENT', 'ANIMALS', 'OTHER', name='charitycategory'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('charity_category_association',
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['charity_categories.id'], ),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], ),
    sa.PrimaryKeyConstraint('charity_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charity_category_association')
    op.drop_table('charity_categories')
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charities_name'))

    op.drop_table('charities')
    # ### end Alembic commands ###
