"""Add LiturgicalDay model for calendar persistence

Revision ID: eceae114776c
Revises: bfe06e81c0c6
Create Date: 2025-08-26 09:06:34.838321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eceae114776c'
down_revision = 'bfe06e81c0c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liturgical_days',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False, comment="Nation, Diocese, or 'GR' for General Roman"),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('grade_name', sa.String(length=100), nullable=True),
    sa.Column('liturgical_season', sa.String(length=50), nullable=True),
    sa.Column('full_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'region')
    )
    with op.batch_alter_table('liturgical_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liturgical_days_liturgical_season'), ['liturgical_season'], unique=False)
        batch_op.create_index(batch_op.f('ix_liturgical_days_year'), ['year'], unique=False)
        batch_op.create_index('ix_liturgical_days_year_region', ['year', 'region'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liturgical_days', schema=None) as batch_op:
        batch_op.drop_index('ix_liturgical_days_year_region')
        batch_op.drop_index(batch_op.f('ix_liturgical_days_year'))
        batch_op.drop_index(batch_op.f('ix_liturgical_days_liturgical_season'))

    op.drop_table('liturgical_days')
    # ### end Alembic commands ###
